#!/bin/sh

if ! [ -f `which npm` ]; then
    echo 'npm is required';
fi

if ! [ -f `which bower` ]; then
    echo 'bower is required';
fi

npm install
bower install

if ! [ -f `which grunt` ]; then
    echo 'Grunt is required';
fi
